### ISSUE TITLE
Dab failing to build due to golangci-lint errors 

### ISSUE THREAD

**Issue by Lachlan-S** [Nekroze/dab#340]
### Describe the bug

When building dab, either through circleci or a local dev environment, the build process fails with golangci-lint not being able to run megacheck due to compilation errors in packages within the go package main. Examples of the errors have been included in the Example section.

### To Reproduce

1. clone the dab repo
2. run ./scripts/build.sh.

### Expected behavior

Dab should successfully build without running into any golangci-lint errors, on both ci and a local dev environment.

### Example

Examples of the error produced:
```
level=warning msg="[runner/megacheck] Can't run megacheck because of compilation errors in packages [github.com/Nekroze/dab]: apps.go:1: /usr/local/go/src/strings/strings.s:5:54: expected ';', found 'EOF' and 11 more errors: run `golangci-lint run --no-config --disable-all -E typecheck` to see all errors"
apps.go:1: /usr/local/go/src/runtime/asm.s:5:1: illegal character U+0023 '#' (typecheck)
package main

WARN [runner/megacheck] Can't run megacheck because of compilation errors in packages [github.com/Nekroze/dab]: apps.go:1: /usr/local/go/src/sync/atomic/asm.s:7:1: illegal character U+0023 '#' and 11 more errors: run `golangci-lint run --no-config --disable-all -E typecheck` to see all errors 
apps.go:1: /usr/local/go/src/runtime/asm.s:5:1: illegal character U+0023 '#' (typecheck)
```

**Comment by Lachlan-S** [comment]
This issue is related to the failed build after merging pull request #320 to master, and the failed build on the Wednesday morning stable update pull request (#339).
